config/routes.rb
Ineke5::Application.routes.draw do
  resources :overzichts

  resources :contactpaginas

  resources :homes

  get 'work/index'

  get 'contacts/new'

  get 'contacts/create'

  get 'paginas' => 'blogs#index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles

  devise_for :users
  root "pages#home"

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
  end

  get 'users' => 'users#index'

  get "/404" => "errors#not_found"
  get "/422" => "errors#unacceptable"
  get "/500" => "errors#internal_error"

  get 'contact' => 'contacts#new'
  resources "contacts", only: [:new, :create]

  get 'overview' => 'articles#overview'

  resources :blogs , :path => '', :only => [:show, :update, :destroy]
  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
	extend FriendlyId
    friendly_id :title, use: :slugged

    validates :title, :body, presence: { :message => "Mag niet leeg zijn." }
    validates :title, :body, length:   { minimum: 2, :message => "Moet minimaal 2 tekens zijn." }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  def index
    @blogs = Blog.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
  end

  def show
    render :layout => 'custom'
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to @blog, notice: 'Page was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
      if @blog.update(blog_params)
        redirect_to @blog, notice: 'Blog was successfully updated.' 
      else
        render action: 'edit' 
      end
  end

  def destroy
    @blog.destroy
    redirect_to paginas_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :slug)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog, html: { multipart: true } do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.cktext_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<% provide(:title, 'Bewerk pagina') %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Bewerk pagina</h1>
    </div>
  </div>
  <div class="panel-body">
  	<%= render 'form' %>
  </div>  
  <div class="panel-footer">
  	<%= link_to 'Show', @blog %> |
  	<%= link_to 'Back', paginas_path %>
  </div>
</div>

app/views/blogs/index.html.erb
<% provide(:title, "Pagina's") %>

<div class="panel panel-default">
  <div class="panel-heading"><h1>Pagina's (<%= @blogs.count %>)</h1></div>
  <div class="panel-body">
    <% if user_signed_in? %>
    <%= link_to("Nieuw artikel", [:new, :blog], :class => 'btn btn-primary') %>
    <% end %>
  </div>
<table class="table table-hover">
  <thead>
  <tr>
    <th>Titel</th>
    <th>Auteur</th>
    <th></th>
  </tr>
  </thead>
  <% @blogs.each do |blog| %>
  <tbody>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.user.username if blog.user %></td>
      <td>
        <div class="btn-group">
  <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
    Opties <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li>
      <%= link_to blog_path(blog) do %>
        <span class="glyphicon glyphicon-eye-open"></span> Toon pagina
      <% end %>
      </li>    
    <li>
      <%= link_to edit_blog_path(blog) do %>
        <span class="glyphicon glyphicon-edit"></span> Bewerk pagina
      <% end %>
      </li>
    <li class="divider"></li>
    <li>
      <%= link_to blog, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-trash"></span> Verwijder pagina
      <% end %>
    </li>
  </ul>
</div>
      </td>
    </tr>
  </tbody>
  <% end %>
  </table>
  <div class="panel-footer">
    <div class="center">
      <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<% provide(:title, 'Nieuwe pagina') %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Nieuwe pagina</h1>
    </div>
  </div>
  <div class="panel-body">
  	<%= render 'form' %>
  </div>  
  <div class="panel-footer">
  	<%= link_to 'Back', paginas_path %>
  </div>
</div>

app/views/blogs/show.html.erb
<% provide(:title, @blog.title) %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1><%= @blog.title %></h1>
    </div>
  </div>
  <div class="panel-body">

	<p>
	  <%= (@blog.body).html_safe %>
	</p>

  </div>  
  <div class="panel-footer">
  	<% if current_user && @blog.user == current_user %>
  	<%= link_to 'Edit', edit_blog_path(@blog) %> |
  	<%= link_to 'Back', paginas_path %>
  	<% end %>
  </div>
</div>