config/routes.rb
Ineke5::Application.routes.draw do
  resources :overzichts

  resources :contactpaginas

  resources :homes

  get 'work/index'

  get 'contacts/new'

  get 'contacts/create'

  get 'paginas' => 'blogs#index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles

  devise_for :users
  root "pages#home"

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
  end

  get 'users' => 'users#index'

  get "/404" => "errors#not_found"
  get "/422" => "errors#unacceptable"
  get "/500" => "errors#internal_error"

  get 'contact' => 'contacts#new'
  resources "contacts", only: [:new, :create]

  get 'overview' => 'articles#overview'

  resources :blogs , :path => '', :only => [:show, :update, :destroy]
  resources :blogs

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader

	extend FriendlyId
    friendly_id :title, use: :slugged

    validates :title, :body, :summary, :image, presence: { :message => "Mag niet leeg zijn." }
    validates :title, :body, :summary, length:   { minimum: 2, :message => "Moet minimaal 2 tekens zijn." }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :overview]

  def index
    @articles = Article.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    @overzichts = Overzicht.all
  end

  def show
    render :layout => 'custom'
  end

  def new
    @article = current_user.articles.build
  end

  def edit
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url
  end

  def overview
    @overzichts = Overzicht.find(1)
    @articles = Article.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    render :layout => 'articles'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :image, :remote_image_url, :image_cache, :summary, :slug)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def wrap(content)
    sanitize((content.split.map{ |s| wrap_long_string(s) }.join(' ')).html_safe)
  end

  private

    def wrap_long_string(text, max_width = 10)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
end

app/views/articles/_article.html.erb
<div id="articles" class="transitions-enabled">
  <% @articles.each do |article| %>
    <div class="box panel panel-default">
        <div class="panel-heading">
            <h2><%= wrap(article.title) %></h2>
        </div>
        <%= link_to article_path(article) do %>
          <%= image_tag article.image_url(:medium).to_s, class: "img-responsive" %>
        <% end %>
        <div class="panel-body">
            <%= article.summary %><br>
        </div>
        <div class="panel-footer">
            <%= link_to 'Lees meer', article_path(article) %> 
            <% if user_signed_in? %>
             | <%= link_to 'Bewerk', edit_article_path(article) %> | 
              <%= link_to 'Verwijder', article, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_for @article, html: { multipart: true } do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :summary %><br>
    <%= f.text_area :summary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.cktext_area :body, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :image %><br />
    <%= image_tag @article.image.url(:small) if @article.image? %>
    <%= f.file_field :image, class: "form-control" %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-group">
    <%= f.label :remote_image_url, "or Image URL" %>
    <%= f.text_field :remote_image_url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, 'Bewerk artikel') %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Bewerk artikel</h1>
    </div>
  </div>
  <div class="panel-body">
  	<%= render 'form' %>
  </div>  
  <div class="panel-footer">
  	<%= link_to 'Show', @article %> |
  	<%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/articles/index.html.erb
<% provide(:title, 'Artikelen') %>

<div class="panel panel-default">
  <div class="panel-heading"><h1>Artikelen (<%= @articles.count %>)</h1></div>
  <div class="panel-body">
    <% if user_signed_in? %>
    <%= link_to("Nieuw artikel", [:new, :article], :class => 'btn btn-primary') %>
    <% end %>
  </div>
<table class="table table-hover">
  <thead>
  <tr>
    <th>Afbeelding</th>
    <th>Titel</th>
    <th>Auteur</th>
    <th></th>
  </tr>
  </thead>
  <% @articles.each do |article| %>
  <tbody>
    <tr>
      <td><%= image_tag article.image.url(:thumb) %></td>
      <td><%= article.title %></td>
      <td><%= article.user.username if article.user %></td>
      <td>
        <div class="btn-group">
  <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
    Opties <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li>
      <%= link_to article_path(article) do %>
        <span class="glyphicon glyphicon-eye-open"></span> Toon artikel
      <% end %>
      </li>    
    <li>
      <%= link_to edit_article_path(article) do %>
        <span class="glyphicon glyphicon-edit"></span> Bewerk artikel
      <% end %>
      </li>
    <li class="divider"></li>
    <li>
      <%= link_to article, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-trash"></span> Verwijder artikel
      <% end %>
    </li>
  </ul>
</div>
      </td>
    </tr>
  </tbody>
  <% end %>
  </table>
  <div class="panel-footer">
    <div class="center">
      <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><h1>Overzichtspaginakoppen (<%= @overzichts.count %>)</h1></div>
  <div class="panel-body">
    <% if user_signed_in? %>
    <%= link_to("Nieuw Overzichtspaginakop", [:new, :overzicht], :class => 'btn btn-primary') %>
    <% end %>
  </div>
<table class="table table-hover">
  <thead>
  <tr>
    <th>Titel</th>
    <th></th>
  </tr>
  </thead>
  <% @overzichts.each do |overzicht| %>
  <tbody>
    <tr>
      <td><%= overzicht.title %></td>
      <td>
        <div class="btn-group">
  <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
    Opties <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li>
      <%= link_to overzicht_path(overzicht) do %>
        <span class="glyphicon glyphicon-eye-open"></span> Toon overzicht
      <% end %>
      </li>    
    <li>
      <%= link_to edit_overzicht_path(overzicht) do %>
        <span class="glyphicon glyphicon-edit"></span> Bewerk overzicht
      <% end %>
      </li>
  </ul>
</div>
      </td>
    </tr>
  </tbody>
  <% end %>
  </table>
  <div class="panel-footer">
  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, 'Nieuw artikel') %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Nieuw artikel</h1>
    </div>
  </div>
  <div class="panel-body">
  	<%= render 'form' %>
  </div>  
  <div class="panel-footer">
  	<%= link_to 'Back', articles_path %>
  </div>
</div>

app/views/articles/overview.html.erb
<% provide(:title, 'Artikelen') %>

<div class="jumbotron center">
  <% if @overzichts.title? %>
    <h1><%= @overzichts.title %></h1>
  <% else %>
    <h1>Our work</h1>
  <% end %>
  <% if @overzichts.body? %>
    <p><%= (@overzichts.body).html_safe %></p>
  <% else %>
    <p>Below, you will find a selection of our work. For more information, click on the link to visit the dedicated page. Once you're there, feel free to let us know what you think by placing a comment. Alternatively, send us a message through the <%= link_to 'contact form', contact_path %>.</p>
  <% end %>
  <% if user_signed_in? %>
    <br>
    <p>
      <%= back_to articles_path %>
    </p>
  <% end %>
</div>
    <%= render 'article' %>

    <div class="center">
      <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    </div>

app/views/articles/overview.js.erb
$boxes = $('<%= j render(@articles) %>')

$('#articles').append( $boxes ).imagesLoaded( function(){
  $('#articles').masonry( 'reload');
});
<% if @articles.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@articles) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1><%= wrap(@article.title) %></h1>
    </div>
  </div>
  <div class="panel-body">

	<p>
	<%= image_tag @article.image_url(:medium).to_s, class: "img-responsive" %>
	</p>

	<p>Geplaatst door <strong><%= @article.user.username if @article.user %></strong> op <%= @article.created_at.strftime("%d/%m/%Y") %> om <%= @article.created_at.strftime("%H:%M") %></p>

	<p>
	  <%= (@article.body).html_safe %>
	</p>

  </div>  
  <div class="panel-footer">
  	<% if current_user && @article.user == current_user %>
  	<%= link_to 'Edit', edit_article_path(@article) %> |
  	<% end %>
  	<%= link_to 'Back', overview_path %>
  </div>
</div>