config/routes.rb
Ineke5::Application.routes.draw do
  resources :overzichts

  resources :contactpaginas

  resources :homes

  get 'work/index'

  get 'contacts/new'

  get 'contacts/create'

  get 'paginas' => 'blogs#index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles

  devise_for :users
  root "pages#home"

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
  end

  get 'users' => 'users#index'

  get "/404" => "errors#not_found"
  get "/422" => "errors#unacceptable"
  get "/500" => "errors#internal_error"

  get 'contact' => 'contacts#new'
  resources "contacts", only: [:new, :create]

  get 'overview' => 'articles#overview'

  resources :blogs , :path => '', :only => [:show, :update, :destroy]
  resources :blogs

end

app/models/contactpagina.rb
class Contactpagina < ActiveRecord::Base
end

app/controllers/contactpaginas_controller.rb
class ContactpaginasController < ApplicationController
  before_action :set_contactpagina, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @contactpaginas = Contactpagina.all
  end

  def show
  end

  def new
    @contactpagina = Contactpagina.new
  end

  def edit
  end

  def create
    @contactpagina = Contactpagina.new(contactpagina_params)
      if @contactpagina.save
        redirect_to @contactpagina, notice: 'Contactpagina was successfully created.' 
      else
        render action: 'new' 
      end
  end

  def update
      if @contactpagina.update(contactpagina_params)
        redirect_to @contactpagina, notice: 'Contactpagina was successfully updated.'
      else
        render action: 'edit' 
      end
  end

  def destroy
    @contactpagina.destroy
    redirect_to contactpaginas_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contactpagina
      @contactpagina = Contactpagina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contactpagina_params
      params.require(:contactpagina).permit(:title, :body)
    end
end

app/helpers/contactpaginas_helper.rb
module ContactpaginasHelper
end

app/views/contactpaginas/_form.html.erb
<%= form_for @contactpagina, html: { multipart: true } do |f| %>
  <% if @contactpagina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contactpagina.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @contactpagina.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", autofocus: true %>
  </div>


  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.cktext_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/contactpaginas/edit.html.erb
<% provide(:title, 'Bewerk contactpagina') %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Bewerk contactpagina</h1>
    </div>
  </div>
  <div class="panel-body">
  	<%= render 'form' %>
  </div>  
  <div class="panel-footer">
  	<%= link_to 'Show', @contactpagina %> |
  	<%= link_to 'Back', contactpaginas_path %>
  </div>
</div>

app/views/contactpaginas/index.html.erb
<% provide(:title, 'Contactpaginas') %>

<div class="panel panel-default">
  <div class="panel-heading"><h1>Contactpagina's (<%= @contactpaginas.count %>)</h1></div>
  <div class="panel-body">
    <% if user_signed_in? %>
    <%= link_to("Nieuw artikel", [:new, :contactpagina], :class => 'btn btn-primary') %>
    <% end %>
  </div>
<table class="table table-hover">
  <thead>
  <tr>
    <th>Titel</th>
    <th></th>
  </tr>
  </thead>
  <% @contactpaginas.each do |contactpagina| %>
  <tbody>
    <tr>
      <td><%= contactpagina.title %></td>
      <td>
        <div class="btn-group">
  <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
    Opties <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li>
      <%= link_to contactpagina_path(contactpagina) do %>
        <span class="glyphicon glyphicon-eye-open"></span> Toon contactpagina
      <% end %>
      </li>    
    <li>
      <%= link_to edit_contactpagina_path(contactpagina) do %>
        <span class="glyphicon glyphicon-edit"></span> Bewerk contactpagina
      <% end %>
      </li>
  </ul>
</div>
      </td>
    </tr>
  </tbody>
  <% end %>
  </table>
  <div class="panel-footer">
  </div>
</div>

app/views/contactpaginas/new.html.erb
<% provide(:title, 'Nieuwe contactpagina') %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Nieuwe contactpagina</h1>
    </div>
  </div>
  <div class="panel-body">
  	<%= render 'form' %>
  </div>  
  <div class="panel-footer">
  	<%= link_to 'Back', contactpaginas_path %>
  </div>
</div>

app/views/contactpaginas/show.html.erb
<% provide(:title, @contactpagina.title) %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1><%= wrap(@contactpagina.title) %></h1>
    </div>
  </div>
  <div class="panel-body">

	<p>Geplaatst op <%= @contactpagina.created_at.strftime("%d/%m/%Y") %> om <%= @contactpagina.created_at.strftime("%H:%M") %></p>

	<p>
	  <%= (@contactpagina.body).html_safe %>
	</p>

  </div>  
  <div class="panel-footer">
  	<%= link_to 'Edit', edit_contactpagina_path(@contactpagina) %> |
  	<%= link_to 'Back', contactpaginas_path %>
  </div>
</div>