config/routes.rb
Ineke5::Application.routes.draw do
  resources :overzichts

  resources :contactpaginas

  resources :homes

  get 'work/index'

  get 'contacts/new'

  get 'contacts/create'

  get 'paginas' => 'blogs#index'

  mount Ckeditor::Engine => '/ckeditor'
  resources :articles

  devise_for :users
  root "pages#home"

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
  end

  get 'users' => 'users#index'

  get "/404" => "errors#not_found"
  get "/422" => "errors#unacceptable"
  get "/500" => "errors#internal_error"

  get 'contact' => 'contacts#new'
  resources "contacts", only: [:new, :create]

  get 'overview' => 'articles#overview'

  resources :blogs , :path => '', :only => [:show, :update, :destroy]
  resources :blogs

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader

	extend FriendlyId
    friendly_id :title, use: :slugged

    validates :title, :body, :summary, :image, presence: { :message => "Mag niet leeg zijn." }
    validates :title, :body, :summary, length:   { minimum: 2, :message => "Moet minimaal 2 tekens zijn." }
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
	extend FriendlyId
    friendly_id :title, use: :slugged

    validates :title, :body, presence: { :message => "Mag niet leeg zijn." }
    validates :title, :body, length:   { minimum: 2, :message => "Moet minimaal 2 tekens zijn." }
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Nieuw bericht van #{name}",
      :to => "info@doamer.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/contactpagina.rb
class Contactpagina < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/overzicht.rb
class Overzicht < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles, dependent: :destroy
  has_many :blogs, dependent: :destroy

  validates :first_name, :last_name, :username, :email, :presence => { :message => "Mag niet leeg zijn." }
  validates :username, uniqueness: { case_sensitive: false, message: "Is al in gebruik." }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX, message: "Is ongeldig." },
                    uniqueness: { case_sensitive: false, message: "Is al in gebruik." }
  validates :password, length: { minimum: 6, message: "Moet minimaal 6 tekens zijn." }, :on => :create
  validates :password_confirmation, presence: { :message => "Wachtwoorden komen niet overeen." }, :on => :create
  validates :password, confirmation: { :message => "Wachtwoorden komen niet overeen." }

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  def index
    @blogs = Blog.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 4)
  end

  def show
    render :layout => 'custom'
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to @blog, notice: 'Page was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
      if @blog.update(blog_params)
        redirect_to @blog, notice: 'Blog was successfully updated.' 
      else
        render action: 'edit' 
      end
  end

  def destroy
    @blog.destroy
    redirect_to paginas_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :slug)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
  	render status: 404, :layout => 'custom'
  end

  def unacceptable
  	render :status => 422, :layout => 'custom'
  end

  def internal_error
  	render :status => 500, :layout => 'custom'
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @homes = Home.all
  end

  def show
  end

  def new
    @home = Home.new
  end

  def edit
  end

  def create
    @home = Home.new(home_params)
      if @home.save
        redirect_to @home, notice: 'Home was successfully created.'
      else
        render action: 'new'
      end
  end

  def update
      if @home.update(home_params)
        redirect_to @home, notice: 'Home was successfully updated.' 
      else
        render action: 'edit' 
      end
  end

  def destroy
    @home.destroy
      redirect_to homes_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@homes = Home.find(1)
    render :layout => 'custom'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order("created_at DESC")
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ineke Vosman"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def back_to(path)
    link_to("&laquo; Terug".html_safe, path, :class => 'btn btn-default')
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def wrap(content)
    sanitize((content.split.map{ |s| wrap_long_string(s) }.join(' ')).html_safe)
  end

  private

    def wrap_long_string(text, max_width = 10)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/overzichts_helper.rb
module OverzichtsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
  <small>
    Ineke Vosman © <%= Time.now.year %>
  </small>
  <nav>
    <ul>
	  <small>
	    Realisatie door <a href="http://www.pesolari.com">Pesolari Group</a>
	  </small>
    </ul>
  </nav>
</div><!--container-->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Ineke Vosman</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% for blog in Blog.all %>
           <li><%= link_to blog.title, blog %></li>
        <% end %>
        <li><%= link_to "Artikelen", overview_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Beheer<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Artikeloverzicht", articles_path %></li>
              <li><%= link_to 'Paginabeheer', paginas_path %></li>
              <li><%= link_to 'Homepagina', homes_path %></li>
              <li><%= link_to 'Contactpagina', contactpaginas_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name %> <%= current_user.last_name %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <span class="glyphicon glyphicon-user"></span> Accountinstellingen
              <% end %>
            </li> 
            <li>
              <%= link_to users_path do %>
                Gebruikersoverzicht
              <% end %>
            </li> 
            <li class="divider"></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <span class="glyphicon glyphicon-log-out"></span> Log out
              <% end %>
            </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", sign_in_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="/keys.ico" />
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "ckeditor/ckeditor.js", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/articles.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="/keys.ico" />
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "articles", media: "all", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</html>

app/views/layouts/custom.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="/keys.ico" />
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
      <div class="col-xs-6"></div>
      <div class="col-xs-6">
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
      </div>
      <div class="push"></div>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="jumbotron center">


<% if @homes.title? %>
  <h1><%= @homes.title %></h1>
<% else %>
  <h1>Welkom op Ineke Vosman.nl!</h1>
<% end %><br>

<% if @homes.body? %>
  <p><%= (@homes.body).html_safe %></p>
<% else %>
  <p>Welkom op Ineke Vosman.nl!</p>
<% end %>
    <% if user_signed_in? %>
    <br>
  <p>
    <%= back_to homes_path %>
  </p>
<% end %>
</div>